const WORDS = [
    'apple',
    'banana',
    'orange',
    'grape',
    'melon',
    'lemon',
    'lime',
    'pear',
    'peach',
    'plum',
    'strawberry',
    'blueberry',
    'raspberry',
    'blackberry',
    'watermelon',
    'pineapple',
    'mango',
    'kiwi',
    'coconut',
    'avocado',
    'cherry',
    'apricot',
    'papaya',
    'cantaloupe',
    'honeydew',
    'pomegranate',
    'persimmon',
    'fig',
    'pumpkin',
    'squash',
    'cucumber',
    'tomato',
    'potato',
    'carrot',
    'broccoli',
    'cauliflower',

    'cat',
    'dog',
    'bird',
    'fish',
    'horse',
    'cow',
    'pig',
    'sheep',
    'goat',
    'chicken',
    'duck',
    'rabbit',
    'squirrel',
    'bear',
    'lion',
    'tiger',
    'monkey',
    'elephant',
    'giraffe',
    'zebra',
    'kangaroo',
    'koala',
    'panda',
    'penguin',
    'whale',
    'dolphin',
    'shark',

    'airplane',
    'car',
    'train',
    'bus',
    'truck',
    'motorcycle',
    'bicycle',
    'boat',
    'ship',
    'submarine',
    'helicopter',
    'rocket',
    'aircraft',
    'spaceship',
    'scooter',
    'skateboard',
    'snowmobile',
    'tractor',
    'ambulance',
    'firetruck',
    'policecar',
    'taxi',
    'van',
    'limousine',
    'ferrari',
    'lamborghini',
    'bugatti',
    'tesla',
    'jeep',
    'mazda',
    'toyota',
    'honda',
    'nissan',
    'ford',
    'chevrolet',
    'dodge',
    'chrysler',
    'jeep',
    'volkswagen',
    'audi',
    'bmw',
    'mercedes',
    'porsche',
    'lexus',
    'acura',
    'infiniti',
    'kia',
    'hyundai',
    'subaru',
]

const getRandomWordThatIsntInList = list => {
    let word = WORDS[Math.floor(Math.random() * WORDS.length)];

    while (list.includes(word)) {
        word = WORDS[Math.floor(Math.random() * WORDS.length)];
    }

    return word;
}

export {
    WORDS,
    getRandomWordThatIsntInList
}